### ISSUE TITLE
Question on some parameters used in utils.py

### ISSUE THREAD

**Issue by VishaalVenkatesh** [vmtang11/deep_rl_atari#1]
What are the fire_first and no_ops variables in utils.py? I found no mention of it in the paper:(

`class RepeatActionAndMaxFrame(gym.Wrapper):

    def __init__(self, env = None, repeat = 4, clip_rewards = False, no_ops = 0, fire_first = False):  # paper repeats agents actions for 4 steps. Repeating action and playing game cheaper than choosing action
        super(RepeatActionAndMaxFrame, self).__init__(env)
        self.repeat = repeat
        self.shape = env.observation_space.low.shape        # lower bounds of observation space. It is an array of 4 values and is the negative of the high.
        self.frame_buffer = np.zeros_like((2, self.shape))  # returns 2 arrays with zeros in the shape of 'shape'
        self.clip_rewards = clip_rewards                    # clip takes the reward and makes it -1, 1, or 0 (no reward).
        self.no_ops = no_ops
        self.fire_first = fire_first`

**Comment by vmtang11** [comment]
`no_ops` is the number of operations to take and `fire_first` is a boolean value for if the first action to take is to fire.
